### ISSUE TITLE
no longer works on python 3.14

### ISSUE THREAD

**Issue by glyph** [anachronic/importmagic.el#31]
```
deferred error : (error "\"AttributeError(\\\"module 'ast' has no attribute 'Str'\\\")\"")
```

this makes sense, as 

```
$ python3.13 -c 'from ast import Str'
<string>:1: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
$ python3.14 -c 'from ast import Str'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from ast import Str
ImportError: cannot import name 'Str' from 'ast' (/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/ast.py)
```

**Comment by Ajaypatel1234** [comment]
Any update on fixing this issue?

**Comment by smemsh** [comment]
looks like this can be fixed using `ast.Constant` rather than `ast.Str` as per https://docs.python.org/3/whatsnew/3.12.html#pending-removal-in-python-3-14

**Comment by glyph** [comment]
> looks like this can be fixed using `ast.Constant` rather than `ast.Str` as per https://docs.python.org/3/whatsnew/3.12.html#pending-removal-in-python-3-14

It has already been fixed: https://github.com/alecthomas/importmagic/issues/68

I'm closing this now because `importmagic.el` does inherit that fix.
